# Generated by Django 2.2.4 on 2019-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
